spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=eventhub
spring.datasource.password=eventhub

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration